BOOK SOURCE Django-Design-Patterns-and-Best-Practices-Second-Edition-master/src/formschapter/urls.py
from django.urls import path
from . import views

app_name = 'formschapter'

urlpatterns = [
    path(r'forms/',
         views.FormView.as_view(),
         name="forms"),

    path('cbv-form/',
         views.ClassBasedFormView.as_view(),
         name="cbv-form"),

    path('gfv-form/',
         views.GenericFormView.as_view(),
         name="gfv-form"),


    path('newsletter-form/',
         views.NewsletterView.as_view(),
         name="newsletter-form"),


    path('impdates/<int:pk>/',
         views.ImpDateDetail.as_view(),
         name="impdate_detail"),

    path('impdates/create/',
         views.ImpDateCreate.as_view(),
         name="impdate_create"),

    path('impdates/<int:pk>/edit/',
         views.ImpDateUpdate.as_view(),
         name="impdate_update"),

    path('impdates/<int:pk>/delete/',
         views.ImpDateDelete.as_view(),
         name="impdate_delete"),

    path('impdates/',
         views.ImpDateList.as_view(),
         name="impdate_list"),
]

BOOK SOURCE Django-Design-Patterns-and-Best-Practices-Second-Edition-master/src/profiles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('me/', views.ShowProfile.as_view(), name='show_me'),
    path('<slug:slug>/', views.ShowProfile.as_view(),
         name='show_user'),
]

BOOK SOURCE Django-Design-Patterns-and-Best-Practices-Second-Edition-master/src/formschapter/models.py
from django.db import models
from django.urls import reverse


class ImportantDate(models.Model):
    date = models.DateField()
    desc = models.CharField(max_length=100)

    def __str__(self):
        return "{} - {}".format(self.date, self.desc)

    def get_absolute_url(self):
        return reverse('formschapter:impdate_detail', args=[str(self.pk)])

    class Meta:
        ordering = ('-date',)

BOOK SOURCE Django-Design-Patterns-and-Best-Practices-Second-Edition-master/src/formschapter/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from . import models


class PersonDetailsForm(forms.Form):
    name = forms.CharField(max_length=100)
    age = forms.IntegerField()

    def __init__(self, *args, **kwargs):
        vip = kwargs.pop("vip", False)
        super().__init__(*args, **kwargs)

        # Are you a VIP?
        if vip:
            self.fields["first_class"] = forms.BooleanField(
                label="Fly First Class?",
                required=False,
                initial=True,
                help_text="First-class only offered to VIPs")

        self.helper = FormHelper(self)
        self.helper.layout.append(Submit('submit', 'Submit'))


class NewsLetterForm(forms.Form):
    email = forms.EmailField()

    def __init__(self, *args, **kwargs):
        submit_btn_name = kwargs.pop('submit_btn_name', 'subscribe_butn')
        submit_btn_value = kwargs.pop('submit_btn_value', 'Subscribe')

        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout.append(Submit(name=submit_btn_name,
                                         value=submit_btn_value))


class SubscribeForm(NewsLetterForm):

    def __init__(self, *args, **kwargs):
        kwargs['submit_btn_name'] = 'subscribe_butn'
        kwargs['submit_btn_value'] = 'Subscribe'
        super().__init__(*args, **kwargs)


class UnSubscribeForm(NewsLetterForm):

    def __init__(self, *args, **kwargs):
        kwargs['submit_btn_name'] = 'unsubscribe_butn'
        kwargs['submit_btn_value'] = 'UnSubscribe'
        super().__init__(*args, **kwargs)


class ImportantDateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.layout.append(Submit('save', 'Save'))

    class Meta:
        model = models.ImportantDate
        fields = ["date", "desc"]

BOOK SOURCE Django-Design-Patterns-and-Best-Practices-Second-Edition-master/src/formschapter/views.py
from django.views import generic
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from braces.views import StaticContextMixin
from .forms import PersonDetailsForm
from .forms import SubscribeForm, UnSubscribeForm
from .forms import ImportantDateForm
from . import models


class FormView(StaticContextMixin, generic.TemplateView):
    template_name = "forms.html"
    static_context = {"form": PersonDetailsForm()}


class ClassBasedFormView(generic.View):
    template_name = 'cbv-form.html'

    def get(self, request):
        form = PersonDetailsForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = PersonDetailsForm(request.POST)
        if form.is_valid():
            # Success! We can use form.cleaned_data now
            return redirect('home')
        else:
            # Invalid form! Reshow the form with error highlighted
            return render(request, self.template_name,
                          {'form': form})


class GenericFormView(generic.FormView):
    template_name = 'cbv-form.html'
    form_class = PersonDetailsForm
    success_url = reverse_lazy("home")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        # Check if the logged-in user is a member of "VIP" group
        kwargs["vip"] = self.request.user.groups.filter(name="VIP").exists()
        return kwargs


class NewsletterView(generic.TemplateView):
    subcribe_form_class = SubscribeForm
    unsubcribe_form_class = UnSubscribeForm
    template_name = "newsletter.html"

    def get(self, request, *args, **kwargs):
        kwargs.setdefault("subscribe_form", self.subcribe_form_class())
        kwargs.setdefault("unsubscribe_form", self.unsubcribe_form_class())
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form_args = {
            'data': self.request.POST,
            'files': self.request.FILES,
        }
        if "subscribe_butn" in request.POST:
            form = self.subcribe_form_class(**form_args)
            if not form.is_valid():
                return self.get(request,
                                subscribe_form=form)
            # Use the form.cleaned_data["email"]
            print("Subscribed to {}".format(form.cleaned_data["email"]))
            return redirect("home")
        elif "unsubscribe_butn" in request.POST:
            form = self.unsubcribe_form_class(**form_args)
            if not form.is_valid():
                return self.get(request,
                                unsubscribe_form=form)
            # Use the form.cleaned_data["email"]
            print("Unsubscribed from {}".format(form.cleaned_data["email"]))
            return redirect("home")
        return super().get(request)


# Pattern: CRUD Views

class ImpDateDetail(generic.DetailView):
    model = models.ImportantDate


class ImpDateCreate(generic.CreateView):
    model = models.ImportantDate
    form_class = ImportantDateForm


class ImpDateUpdate(generic.UpdateView):
    model = models.ImportantDate
    form_class = ImportantDateForm


class ImpDateDelete(generic.DeleteView):
    model = models.ImportantDate
    success_url = reverse_lazy("formschapter:impdate_list")


# Non-CRUD
class ImpDateList(generic.ListView):
    model = models.ImportantDate

BOOK SOURCE Django-Design-Patterns-and-Best-Practices-Second-Edition-master/src/formschapter/templates/formschapter/importantdate_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-4">
      <div class="alert alert-danger" role="alert">You are about to delete this important date... It cannot be undone!</div>

      <h2>{{ importantdate.desc }}</h2>
      <p>{{ importantdate.date }}</p>
      <form method="post">
        {% csrf_token %}
        <input type="submit" name="delete" value="Confirm Deletion" class="btn btn-danger"/>
      </form>

    </div>
  </div>
{% endblock content %}

BOOK SOURCE Django-Design-Patterns-and-Best-Practices-Second-Edition-master/src/formschapter/templates/formschapter/importantdate_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

  <div class="row justify-content-center">
    <div class="col-md-4">

      <div class="panel panel-default">
        <div class="panel-body">
          <h2>{{ importantdate.desc }}</h2>
          <p>{{ importantdate.date }}</p>
        </div>
      </div>

      <hr/>
      <p class="pull-right">
        <a href="{% url 'formschapter:impdate_list' %}" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left"></span> Back to list</a>
        <a href="{% url 'formschapter:impdate_update' pk=importantdate.pk %}" class="btn btn-default"><span class="glyphicon glyphicon-edit"></span> Edit</a>
        <a href="{% url 'formschapter:impdate_delete' pk=importantdate.pk %}" class="btn btn-default"><span class="glyphicon glyphicon-remove"></span> Delete</a>
      </p>

      <p></p>
    </div>
  </div>
{% endblock content %}

BOOK SOURCE Django-Design-Patterns-and-Best-Practices-Second-Edition-master/src/formschapter/templates/formschapter/importantdate_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-4">
      <h2>Add an important date</h2>
      {% crispy form %}
    </div>
  </div>
{% endblock content %}

BOOK SOURCE Django-Design-Patterns-and-Best-Practices-Second-Edition-master/src/formschapter/templates/formschapter/importantdate_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

  <div class="row justify-content-center">
    <div class="col-md-4">
      <h1>Important Dates</h1>
      <div class="list-group">
      {% for date in importantdate_list %}
        <a href="{% url 'formschapter:impdate_detail' pk=date.pk%}" class="list-group-item">{{ date.date}} - {{ date.desc }}</a>
      {% empty %}
        <p>None found!</p>
      {% endfor %}
      </div>
      <a href="{% url 'formschapter:impdate_create' %}" class="btn btn-primary">Create New</a>
    </div>
  </div>

{% endblock content %}